### ISSUE TITLE
Save images as 16-bit unsigned integers

### ISSUE THREAD

**Issue by albireox** [UWMRO/evora-server#18]
Images should be saved as `uint16`. For now that can simply be done by recasting the data frame before saving it to the FITS file.

Longer term, we may want to test the `GetAcquiredData16` function instead of the current `GetAcquiredData` that reads as a 32-bit signed integer.

**Comment by seb-cap** [comment]
Was this resolved?

**Comment by albireox** [comment]
Indeed it was!
